site_name: Order of Marzod Documentation
site_description: >-
  Official documentation and foundational texts for the Order of Marzod.
site_author: Order of Marzod
repo_url: https://github.com/DCARTER92/Order-of-Marzod

# Material theme for MkDocs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - content.code.annotate
    - content.tabs.link
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.action.view
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - meta
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tasklist
  - pymdownx.tilde

nav:
  - Home: index.html
  - Books:
      - The Bible: public/books/the_bible-analysis.md
      - The Book of Metal: public/books/the_book-of-metal.md
      - The Book of Air: public/books/the_book-of-air.md
      - The Book of Earth: public/books/the_book-of-earth.md
      - The Book of Water: public/books/the_book-of-water.md
  - Foundational Accords:
      - Core Principle: public/books/The_Foundational_Accords/Core Principle.md
      - Statement of Purpose: public/books/The_Foundational_Accords/Statement of Purpose.md
      - The Degrees and Dignities of the Order: public/books/The_Foundational_Accords/The Degrees and Dignities of the Order.md
      - The Laws of Governance: public/books/The_Foundational_Accords/The Laws of Governance.md
      - The Trials: public/books/The_Foundational_Accords/The Trials.md
      - Trials of Ascension: public/books/The_Foundational_Accords/Trials of Ascension.md
  - Statement of Purpose: public/books/Statement_of_Purpose/Statement of Purpose.md
