# Render deployment configuration for full-stack app

# Web Service: Node.js backend
services:
  - type: web
    name: marzod-server
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true

# Static Site: React frontend (Vite build)
  - type: web
    name: marzod-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeploy: true
